-- common fields
COLUMN MYID FORMAT 99999999 HEADING 'ID';
COLUMN DATETIME FORMAT A20 HEADING 'At';
COLUMN SIGNED_CODE FORMAT A16 HEADING 'By';
COLUMN VALIDATION FORMAT A10 HEADING 'Delete?';

--
COLUMN D_CODE FORMAT A16;
COLUMN D_NAME FORMAT A16;
COLUMN D_NOTE FORMAT A16 TRUNCATE;
