SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;

TTITLE LEFT 'List of User Tables' SKIP 1 LINE;
COLUMN tsname FORMAT A20 HEADING 'Tablespace';
COLUMN tabname FORMAT A32 HEADING 'Tablename';
COLUMN tabcmt FORMAT A80 HEADING 'Comments' TRUNCATE;

SELECT
  atbs.TABLESPACE_NAME AS tsname,
  atbs.TABLE_NAME AS tabname,
  REPLACE(REPLACE(utbcmts.COMMENTS, CHR(13), ''), CHR(10), '\n') AS tabcmt
  FROM ALL_TABLES atbs
         LEFT JOIN USER_TAB_COMMENTS utbcmts
             ON atbs.TABLE_NAME = utbcmts.TABLE_NAME
 ORDER BY tsname, tabname;
