SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;

TTITLE LEFT 'List of User Tablespaces' SKIP 1 LINE;
COLUMN tspname FORMAT A32 HEADING 'Tablespace';

SELECT
  uts.TABLESPACE_NAME AS tspname
  FROM USER_TABLESPACES uts
 ORDER BY tspname;
