SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;

-- TTITLE CENTER 'List of Tables' SKIP 1 LINE;
-- COLUMN no FORMAT 9999 HEADING 'No.';
COLUMN PROPERTY_NAME FORMAT A16 HEADING 'Name';
COLUMN PROPERTY_VALUE FORMAT A16 HEADING 'Value';
COLUMN DESCRIPTION FORMAT A80 HEADING 'Description' TRUNCATE;

SELECT *
  FROM DATABASE_PROPERTIES
 WHERE PROPERTY_NAME IN ('NLS_CHARACTERSET', 'NLS_LANGUAGE', 'NLS_TERRITORY');
