SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;

TTITLE LEFT 'List of User Sequences' SKIP 1 LINE;
COLUMN seqname FORMAT A32 HEADING 'Sequence Name';
COLUMN seqstep FORMAT 999999 HEADING 'Step';
COLUMN seqlast FORMAT 99999999999 HEADING 'Last Number';
COLUMN seqcache FORMAT 999999 HEADING 'Cache Size';

SELECT
  usq.SEQUENCE_NAME AS seqname,
  usq.INCREMENT_BY AS seqstep,
  usq.LAST_NUMBER AS seqlast,
  usq.CACHE_SIZE AS seqcache
  FROM USER_SEQUENCES usq
 ORDER BY seqname;
