SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;

TTITLE LEFT 'List of User Tables' SKIP 1 LINE;
COLUMN tabname FORMAT A32 HEADING 'Table Name';
COLUMN tabcmt FORMAT A80 HEADING 'Comments' TRUNCATE;

-- SELECT MAX(LENGTH(TABLE_NAME)) FROM USER_TABLES;
-- SELECT MAX(LENGTH(COMMENTS)) FROM USER_TAB_COMMENTS;

SELECT
  utbs.TABLE_NAME AS tabname,
  (
    SELECT REPLACE(REPLACE(utbc.COMMENTS, CHR(13), ''), CHR(10), '\n')
      FROM USER_TAB_COMMENTS utbc
     WHERE utbc.TABLE_NAME = utbs.TABLE_NAME AND
           ROWNUM <= 1
  ) AS tabcmt
  FROM USER_TABLES utbs
 ORDER BY tabname;
