-- 查看所有表和视图，以及注释
SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;

-- TTITLE CENTER 'List of Tables' SKIP 1 LINE;
-- COLUMN no FORMAT 9999 HEADING 'No.';
COLUMN tabname FORMAT A32 HEADING 'Name';
COLUMN tabtype FORMAT A6 HEADING 'Type';
COLUMN tabcmt FORMAT A80 HEADING 'Comment' TRUNCATE;

SELECT utbs.TABLE_NAME AS tabname,
       REPLACE(REPLACE(utbcmts.COMMENTS, CHR(13), ''), CHR(10), '\n') AS tabcmt
  FROM USER_TABLES utbs
         LEFT JOIN USER_TAB_COMMENTS utbcmts
             ON utbs.TABLE_NAME = utbcmts.TABLE_NAME
 ORDER BY tabname;
