SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;

TTITLE LEFT 'Database Server Information' SKIP 1 LINE;
COLUMN hostname FORMAT A16 HEADING 'Host';
COLUMN ipaddr FORMAT A16 HEADING 'IP';
COLUMN servid FORMAT A16 HEADING 'SID';

SELECT
  UTL_INADDR.GET_HOST_NAME AS hostname,
  UTL_INADDR.GET_HOST_ADDRESS AS ipaddr,
  (
    SELECT NAME FROM V$DATABASE
  ) AS servid
  FROM DUAL;
