SET LINESIZE 32767;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;
SET VERIFY OFF
SET TERMOUT OFF;

COLUMN dummy_sqlcnt NEW_VALUE sqlcnt;
SELECT NVL(TO_NUMBER('&1'), 10) AS dummy_sqlcnt FROM DUAL;

SET TERMOUT ON;

COLUMN sqltime FORMAT A20 HEADING 'Active Time';
COLUMN sqltext FORMAT A1024 HEADING 'SQL' TRUNCATE;


SELECT TO_CHAR(LAST_ACTIVE_TIME, 'yyyy-mm-dd hh24:mi:ss') AS sqltime,
       SQL_TEXT AS sqltext
  FROM V$SQL WHERE ROWNUM <= &sqlcnt
 ORDER BY LAST_ACTIVE_TIME DESC;
