SET LINESIZE 255;
SET PAGESIZE 50000;
SET FEEDBACK OFF;
SET TAB OFF;
SET TERMOUT OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-mm-dd hh24:mi:ss';
SET TERMOUT ON;

TTITLE LEFT 'List of User Sessions' SKIP 1 LINE;
-- COLUMN logintype FORMAT A10 HEADING 'Type';
COLUMN col01 HEADING 'Login Time';
COLUMN col02 FORMAT A12 HEADING 'User' TRUNCATE;
COLUMN col03 FORMAT A12 HEADING 'Schema' TRUNCATE;
COLUMN col04 FORMAT A12 HEADING 'SID';
COLUMN col05 FORMAT A32 HEADING 'User@Hostname';
COLUMN col06 FORMAT A24 HEADING 'Program' TRUNCATE;
-- COLUMN status FORMAT A8 HEADING 'Status' TRUNCATE;
-- COLUMN state FORMAT A8 HEADING 'State' TRUNCATE;

SELECT
  t1.LOGON_TIME AS col01,
  t1.USERNAME AS col02,
  t1.SCHEMANAME AS col03,
  t1.SERVICE_NAME AS col04,
  t1.OSUSER || '@' || t1.MACHINE AS col05,
  -- t1.STATUS AS status,
  -- t1.STATE AS state,
  t1.PROGRAM AS col06
  FROM V$SESSION t1
 WHERE t1.TYPE = 'USER'
 ORDER BY col01 DESC, col02;
