CREATE TABLESPACE BAMTRI_MES_P01 DATAFILE
  '/oradata/bamtri_mes/p01.dbf'
  SIZE 4096M AUTOEXTEND OFF
  LOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;

CREATE TABLESPACE BAMTRI_MES_P02 DATAFILE
  '/oradata/bamtri_mes/p02.dbf'
  SIZE 8096M AUTOEXTEND OFF
  LOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;

CREATE TEMPORARY TABLESPACE BAMTRI_MES_T01 TEMPFILE
  '/oradata/bamtri_mes/t01.dbf'
  SIZE 2048M AUTOEXTEND OFF
  TABLESPACE GROUP ''
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

CREATE TABLESPACE BAMTRI_MES_MSG01 DATAFILE
  '/oradata/bamtri_mes/msg01.dbf'
  SIZE 2048M AUTOEXTEND OFF
  LOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;

CREATE TABLESPACE BAMTRI_MES_REPORT01 DATAFILE
  '/oradata/bamtri_mes/report01.dbf'
  SIZE 2048M AUTOEXTEND OFF
  LOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;

CREATE TABLESPACE BAMTRI_MES_BLOB01 DATAFILE
  '/oradata/bamtri_mes/blob01.dbf'
  SIZE 2048M AUTOEXTEND OFF
  LOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;

CREATE TABLESPACE BAMTRI_MES_LOG01 DATAFILE
  '/oradata/bamtri_mes/log01.dbf'
  SIZE 1024M AUTOEXTEND OFF
  NOLOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;

CREATE TABLESPACE BAMTRI_MES_LOG02 DATAFILE
  '/oradata/bamtri_mes/log02.dbf'
  SIZE 2048M AUTOEXTEND OFF
  NOLOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;

CREATE TABLESPACE BAMTRI_MES_H01 DATAFILE
  '/oradata/bamtri_mes/h01.dbf'
  SIZE 4096M AUTOEXTEND ON
  LOGGING
  ONLINE
  PERMANENT
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  BLOCKSIZE 8K
  SEGMENT SPACE MANAGEMENT AUTO
  FLASHBACK ON;
