SET LINESIZE 120;
SET PAGESIZE 80;

COLUMN PROPERTY_NAME FORMAT A32 HEADING 'Name';
COLUMN PROPERTY_VALUE FORMAT A32 HEADING 'Value';
COLUMN DESCRIPTION FORMAT A40 HEADING 'Description' TRUNCATE;

SELECT PROPERTY_NAME, PROPERTY_VALUE, DESCRIPTION
  FROM DATABASE_PROPERTIES
 WHERE PROPERTY_NAME LIKE 'NLS_%';
 -- WHERE PROPERTY_NAME IN ('NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET');
