SET LINESIZE 160;

COLUMN PROPERTY_NAME FORMAT A32 HEADING 'Name';
COLUMN PROPERTY_VALUE FORMAT A32 HEADING 'Value';
COLUMN DESCRIPTION FORMAT A80 HEADING 'Description' TRUNCATE;

SELECT PROPERTY_NAME, PROPERTY_VALUE, DESCRIPTION
  FROM DATABASE_PROPERTIES WHERE PROPERTY_NAME LIKE 'NLS_%';
