-- drop all tablespaces
DROP TABLESPACE BAMTRI_MES_P01      INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;
DROP TABLESPACE BAMTRI_MES_P02      INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;
DROP TABLESPACE BAMTRI_MES_MSG01    INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;
DROP TABLESPACE BAMTRI_MES_REPORT01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;
DROP TABLESPACE BAMTRI_MES_BLOB01   INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;
DROP TABLESPACE BAMTRI_MES_LOG01    INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;
DROP TABLESPACE BAMTRI_MES_LOG02    INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;
DROP TABLESPACE BAMTRI_MES_H01      INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINT;

-- drop temporary tablespaces
DROP TABLESPACE BAMTRI_MES_T01 INCLUDING CONTENTS AND DATAFILES;
